name: 自动编译DLL
on: [push, pull_request]  # 推送代码或PR时触发

jobs:
  build:
    runs-on: windows-latest  # 必须用Windows系统

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装.NET Framework 4.8
        uses: microsoft/setup-dotnet@v4
        with:
          dotnet-version: '4.8.x'

      - name: 还原NuGet依赖（安装DllExport）
        run: |
          cd ProcessPathDLL
          nuget restore

      - name: 编译项目
        run: |
          cd ProcessPathDLL
          msbuild /p:Configuration=Release /p:Platform=x86

      - name: 上传编译好的DLL
        uses: actions/upload-artifact@v4
        with:
          name: ProcessPathDLL  # 下载时的文件名
          path: ProcessPathDLL/bin/x86/Release/ProcessPathDLL.dll  # DLL生成路径
