name: 自动编译DLL
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装.NET Framework 4.8 构建工具
        uses: actions/setup-dotnet@v4  # 修正为正确的Action名称
        with:
          dotnet-version: '4.8.x'

      - name: 还原NuGet依赖
        run: |
          cd ProcessPathDLL
          nuget restore

      - name: 编译项目
        run: |
          cd ProcessPathDLL
          msbuild /p:Configuration=Release /p:Platform=x86

      - name: 上传DLL
        uses: actions/upload-artifact@v4
        with:
          name: ProcessPathDLL
          path: ProcessPathDLL/bin/x86/Release/ProcessPathDLL.dll
