name: 自动编译DLL
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 配置Visual Studio构建工具
        uses: microsoft/setup-msbuild@v2

      - name: 安装NuGet工具
        uses: nuget/setup-nuget@v2

      - name: 还原NuGet包（使用packages.config）
        run: nuget restore ProcessPathDLL/ProcessPathDLL.csproj -PackagesDirectory ProcessPathDLL/packages

      - name: 编译项目
        run: msbuild ProcessPathDLL/ProcessPathDLL.csproj /p:Configuration=Release /p:Platform=x86 /p:PlatformTarget=x86

      - name: 上传DLL
        uses: actions/upload-artifact@v4
        with:
          name: ProcessPathDLL
          path: ProcessPathDLL/bin/x86/Release/ProcessPathDLL.dll
