name: 自动编译DLL
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4  # 直接拉取仓库中已有的文件（包括ProcessPathDLL文件夹）

      - name: 安装NuGet工具
        uses: nuget/setup-nuget@v2

      - name: 还原依赖包
        run: nuget restore ProcessPathDLL/ProcessPathDLL.csproj  # 直接使用现有项目文件

      - name: 编译项目
        run: msbuild ProcessPathDLL/ProcessPathDLL.csproj /p:Configuration=Release /p:Platform=x86

      - name: 上传DLL
        uses: actions/upload-artifact@v4
        with:
          name: ProcessPathDLL
          path: ProcessPathDLL/bin/x86/Release/ProcessPathDLL.dll
